"""Checks the Mesh panel restyle: the stats block reads as a tile grid
(gui/qml/panels/MeshPanel.qml, inset wells per DESIGN.md's v2.1
correction -- not floating cards) instead of bare label lines, while
`AppController.meshStats`'s data contract is untouched (that's covered
by the pre-existing gui/tests/test_phase3c_mesh_stats.py, which this
change does not modify).

Note on scope: the per-axis tiles are generated by a Repeater, and
confirmed directly (2026-09-04, same finding as the sidebar tabs in
the Slice 1 reskin) that Repeater-generated delegate items are not
reachable via QObject.findChildren() in this PySide6/Qt build -- true
even for a plain Repeater inside a GridLayout, not just Container
types like TabBar. So this test checks the statically-declared parts
(the total-nodes tile, the two placeholder labels) via the real
rendered tree, and leaves per-axis-tile pixel content to live-app
screenshot verification (see the reskin plan/history.md entries for
that record) rather than a broken introspection technique.
"""
from PySide6.QtCore import QObject
from PySide6.QtWidgets import QApplication

from gui.app import close_engine, create_engine


def _load(app):
    engine, controller = create_engine(app)
    root = engine.rootObjects()[0]
    tabs = root.findChild(QObject, "workbenchTabs")
    tabs.setProperty("currentIndex", 2)  # Mesh tab (Project, Structure, Mesh, ...)
    for _ in range(5):
        app.processEvents()
    return engine, controller, root


def test_mesh_panel_shows_no_data_label_before_any_solve():
    app = QApplication.instance() or QApplication([])
    engine, controller, root = _load(app)
    try:
        grid = root.findChild(QObject, "meshStatsGrid")
        no_data = root.findChild(QObject, "meshStatsNoDataLabel")
        assert grid is not None and no_data is not None
        assert grid.property("visible") is False
        assert no_data.property("visible") is True
    finally:
        close_engine(engine)


def test_mesh_panel_total_tile_shows_real_node_count_after_a_solve():
    app = QApplication.instance() or QApplication([])
    engine, controller, root = _load(app)
    try:
        controller.loadExample("diode_1d")
        for _ in range(10):
            app.processEvents()

        grid = root.findChild(QObject, "meshStatsGrid")
        total_tile = root.findChild(QObject, "meshStatsTotalTile")
        assert grid is not None and total_tile is not None
        assert grid.property("visible") is True
        assert total_tile.property("color") is not None

        stats = controller.meshStats
        assert stats is not None and stats["node_count"] > 0
    finally:
        close_engine(engine)


def test_mesh_panel_stats_tiles_use_inset_well_tokens():
    # Static check on the QML source: the stats block's tiles read as
    # inset wells (Theme.panelAlt/Theme.border, radiusSm) rather than
    # bare label lines or floating cardBg/cardBorder cards -- v2.1
    # correction, DESIGN.md section 2/6: docked stat tiles are not
    # cards, and radius is capped at 3px.
    import os
    qml_path = os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
        "qml", "panels", "MeshPanel.qml",
    )
    text = open(qml_path, encoding="utf-8").read()
    assert "meshStatsGrid" in text
    assert "meshStatsTotalTile" in text
    assert "meshStatsAxisTile" in text
    assert "Theme.panelAlt" in text
    assert "Theme.border" in text
    assert "Theme.cardBg" not in text
    assert "Theme.cardBorder" not in text
