"""Generate desktop/src/views/colormap_tables.hpp from matplotlib's own
colour maps (NATIVE-DESKTOP-PLAN.md 15.17, S5b).

    conda run -n tcad-dev python desktop/tools/gen_colormaps.py

The QML viewport draws with matplotlib, so the native app uses the SAME
256-entry tables, not an approximation: entry i is cmap(i / 255), which
for these N=256 maps is exactly matplotlib's lookup entry i.
gui/tests/test_desktop_colormaps.py re-derives them from matplotlib and
compares, so a regenerated file that drifts fails the suite.
"""
import os

import matplotlib
import numpy as np

MAPS = [("viridis", "Viridis"), ("plasma", "Plasma"), ("inferno", "Inferno"), ("RdBu_r", "RdBuR")]
OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                   "src", "views", "colormap_tables.hpp")


def main():
    lines = [
        "// GENERATED by desktop/tools/gen_colormaps.py from matplotlib "
        f"{matplotlib.__version__} -- do not edit.",
        "// matplotlib's own 256-entry colour maps (NATIVE-DESKTOP-PLAN.md 15.17, S5b):",
        "// entry i = cmap(i / 255). Colour maps encode VALUES, not UI state, so this",
        "// file is exempt from the no-hard-coded-colours gate (test_desktop_theme.py).",
        "#pragma once",
        "",
        "#include <array>",
        "#include <string_view>",
        "",
        "namespace tcad::desktop::colormaps {",
        "",
        "using Table = std::array<std::array<double, 3>, 256>;",
        "",
    ]
    for mpl_name, cpp_name in MAPS:
        cmap = matplotlib.colormaps[mpl_name]
        assert cmap.N == 256, (mpl_name, cmap.N)
        rgba = cmap(np.arange(256) / 255.0)
        lines.append(f"// matplotlib '{mpl_name}'")
        lines.append(f"inline constexpr Table k{cpp_name}{{{{")
        for r, g, b, _a in rgba:
            lines.append(f"    {{{repr(float(r))}, {repr(float(g))}, {repr(float(b))}}},")
        lines.append("}};")
        lines.append("")
    lines.append("struct Named {")
    lines.append("    std::string_view name;  // matplotlib's name")
    lines.append("    const Table* table;")
    lines.append("};")
    lines.append("inline constexpr std::array<Named, %d> kAll{{" % len(MAPS))
    for mpl_name, cpp_name in MAPS:
        lines.append(f'    {{"{mpl_name}", &k{cpp_name}}},')
    lines.append("}};")
    lines.append("")
    lines.append("}  // namespace tcad::desktop::colormaps")
    with open(OUT, "w", newline="\n") as fh:
        fh.write("\n".join(lines) + "\n")
    print("wrote", OUT)


if __name__ == "__main__":
    main()
